package com.study.oops.concepts;

import java.util.Arrays;

/**
 * <p>
 * A record is a special type of class declaration aimed at reducing the
 * boilerplate code. Internally the compiler converts it into a normal class
 * with some restrictions, which makes it different from the typical classes.
 * Java records were introduced with the intention to be used
 * as a fast way to create data carrier classes, i.e. the classes whose
 * objective is to simply contain data and carry it between modules, also known
 * as POJOs (Plain Old Java Objects) and DTOs (Data Transfer Objects).
 * </p>
 * 
 * <pre>
 * When the Java file is compiled by the Java compiler to the bytecode, the .class file produced contains the extended declaration of the record class.
 * * The record gets replaced by class.
 * * The class and its data members gets declared as final. This implies that this class cannot be extended, i.e. cannot be inherited, and is immutable as well.
 * * The class extends java.lang.Record. This means that all records are a subclass of Record defined in java.lang package.
 * * A default constructor gets generated.
 * * Any instance or static methods will be declared as-is.
 * * The toString(), hashCode(), and equals() methods gets auto-generated by the compiler.

 * Some Properties of Records:
 * * You can use nested classes and interfaces inside a record.
 * * You can have nested records too, which will implicitly be static.
 * * A record can implement interfaces.
 * * You can create a generic record class.
 * * It is possible to use local record classes (since Java SE 15).
 * * Records are serializable.
 * </pre>
 * 
 * @version Java SE 14
 */
public class RecordsImpl {

    public enum STANDARD {
        FIRST, SECOND, THIRD
    }

    /**
     * Student Record
     * 
     * @param name
     * @param standard
     * @param marks
     */
    public record Student(String name, STANDARD standard, int marks) {

        /**
         * Constructor
         */
        public Student {
            if (marks < 0 || marks > 100) {
                throw new IllegalArgumentException("Invalid Marks");
            }

            if (standard == null || Arrays.stream(STANDARD.values()).noneMatch(s -> s == standard)) {
                throw new IllegalArgumentException("Invalid Standard");
            }
        }
    }

    public static void main(String[] args) {
        Student s1 = new Student("Ryan", STANDARD.FIRST, 67);
        System.out.println(s1.toString());
        System.out.println(s1.name() + " - " + s1.standard() + " - " + s1.marks());
        Student s2 = new Student("John", STANDARD.SECOND, 104);
        System.out.println(s2);
    }
}
